// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to provide AI-driven insights and suggestions on email campaign performance.
 *
 * - generateEmailCampaignInsights - A function that generates insights and suggestions for email campaigns.
 * - EmailCampaignInsightsInput - The input type for the generateEmailCampaignInsights function.
 * - EmailCampaignInsightsOutput - The return type for the generateEmailCampaignInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EmailCampaignInsightsInputSchema = z.object({
  emailAnalyticsData: z.string().describe('JSON string containing analytics data of email campaigns, including metrics like open rates, click-through rates, bounce rates, and subscriber engagement.'),
});
export type EmailCampaignInsightsInput = z.infer<typeof EmailCampaignInsightsInputSchema>;

const EmailCampaignInsightsOutputSchema = z.object({
  insights: z.string().describe('AI-generated insights based on the email campaign analytics data.'),
  suggestions: z.string().describe('AI-driven suggestions to improve email campaign performance.'),
});
export type EmailCampaignInsightsOutput = z.infer<typeof EmailCampaignInsightsOutputSchema>;

export async function generateEmailCampaignInsights(input: EmailCampaignInsightsInput): Promise<EmailCampaignInsightsOutput> {
  return emailCampaignInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'emailCampaignInsightsPrompt',
  input: {schema: EmailCampaignInsightsInputSchema},
  output: {schema: EmailCampaignInsightsOutputSchema},
  prompt: `You are an AI assistant specializing in email marketing. Analyze the provided email campaign analytics data and provide actionable insights and suggestions for improvement.

Email Campaign Analytics Data: {{{emailAnalyticsData}}}

Based on this data, provide the following:

1.  Insights: Key observations about the campaign's performance.
2.  Suggestions: Concrete steps to enhance future campaigns.

Ensure the suggestions are specific, measurable, achievable, relevant, and time-bound (SMART goals).
`,
});

const emailCampaignInsightsFlow = ai.defineFlow(
  {
    name: 'emailCampaignInsightsFlow',
    inputSchema: EmailCampaignInsightsInputSchema,
    outputSchema: EmailCampaignInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
